import contextvars
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent

# ── inputs ──────────────────────────────────────────────────────────────────
INPUT_DIR = BASE_DIR / "input" / "logs"

# The fixed baseline: hand-maintained "golden parameter list" workbooks,
# bundled inside this package (not generated by any parser run). Three of
# them, one per audit section, so a quarterly refresh of (say) the LTE values
# replaces one file and cannot disturb the other two:
#
#   LTE_GPL_UPDATED.xlsx  one LTE_GPL_<CIRCLE> sheet per circle
#   NR_GPL_UPDATED.xlsx   one NR_GPL_<CIRCLE>  sheet per circle
#   FEATURES.xlsx         a single FEATURESTATE sheet (LTE + NR features)
#
# Both parameter workbooks are split PER CIRCLE — the expected value for a
# parameter differs between circles — so the circle is a required run input
# (config.set_circle) and picks the sheet within each workbook. Features are
# pan-India and live in one sheet.
#
# See log_parser/reference.py for the exact shape each sheet must have.
REFERENCE_DIR = BASE_DIR / "reference"
LTE_REFERENCE_FILE = REFERENCE_DIR / "LTE_GPL_UPDATED.xlsx"
NR_REFERENCE_FILE = REFERENCE_DIR / "NR_GPL_UPDATED.xlsx"
FEATURE_REFERENCE_FILE = REFERENCE_DIR / "FEATURES.xlsx"

LTE_CIRCLE_SHEET_PREFIX = "LTE_GPL_"
NR_CIRCLE_SHEET_PREFIX = "NR_GPL_"
FEATURE_SHEET = "FEATURESTATE"

COMMANDS_FILE = BASE_DIR / "commands" / "GPL_Audit_command_NR_Updated.txt"
COMMANDS_CACHE_PATH = BASE_DIR / "commands" / "commands_cache.json"

OUTPUT_DIR = BASE_DIR / "output"
OUTPUT_FILE = OUTPUT_DIR / "GPL_REFERENCE_AUDIT.xlsx"

# (sheet_name, data_key) — sheet_name is what gets written to the output
# workbook AND what corrections.py reads back out, so these two must agree.
# Only 4 sections exist in this design (the golden workbook only covers LTE/NR
# parameters + one combined feature state list — no eNBInfo/frequency/relation
# sections).
SHEETS: list[tuple[str, str]] = [
    ("Summary", "summary_counts"),
    ("LTE_GPL_AUDIT", "lte_gpl"),
    ("NR_GPL_AUDIT", "nr_gpl_audit"),
    ("Featurestate", "feature_state"),
]

# ── runtime overrides (ContextVar — see original config.py for rationale:
# isolates overlapping asyncio-task / thread runs in a long-lived server
# process from clobbering each other's file selections). ──────────────────
_input_files_var: "contextvars.ContextVar[list[Path] | None]" = contextvars.ContextVar("input_files", default=None)
_circle_var: "contextvars.ContextVar[str | None]" = contextvars.ContextVar("circle", default=None)
_lte_reference_file_var: "contextvars.ContextVar[Path | None]" = contextvars.ContextVar("lte_reference_file", default=None)
_nr_reference_file_var: "contextvars.ContextVar[Path | None]" = contextvars.ContextVar("nr_reference_file", default=None)
_feature_reference_file_var: "contextvars.ContextVar[Path | None]" = contextvars.ContextVar("feature_reference_file", default=None)
_output_file_var: "contextvars.ContextVar[Path | None]" = contextvars.ContextVar("output_file", default=None)
_session_dir_var: "contextvars.ContextVar[Path | None]" = contextvars.ContextVar("session_dir", default=None)


def set_input_files(files: list[Path]) -> None:
    _input_files_var.set(files)


def set_lte_reference_file(path: Path) -> None:
    """Override a baseline workbook for this run only (e.g. validating next
    quarter's file before promoting it). Normally not called — the
    module-level *_REFERENCE_FILE paths are what's used."""
    _lte_reference_file_var.set(path)


def set_nr_reference_file(path: Path) -> None:
    _nr_reference_file_var.set(path)


def set_feature_reference_file(path: Path) -> None:
    _feature_reference_file_var.set(path)


def set_circle(circle: str | None) -> None:
    """Select the circle whose LTE and NR golden sheets this run audits against.

    Normalised to upper case here so callers can pass "hr", "Hr" or "HR" —
    the sheet suffix is upper case in both workbooks. There is no pan-India
    fallback: every parameter sheet is circle-specific, so a run without a
    circle cannot be audited and reference.py raises instead of guessing."""
    circle = str(circle).strip().upper() if circle is not None else ""
    _circle_var.set(circle or None)


def get_circle() -> str | None:
    return _circle_var.get()


def set_output_file(path: Path) -> None:
    _output_file_var.set(path)


def set_session_dir(path: Path) -> None:
    _session_dir_var.set(path)


def get_session_dir() -> Path | None:
    return _session_dir_var.get()


def get_input_files() -> list[Path]:
    files = _input_files_var.get()
    if files is not None:
        return files
    files = sorted(INPUT_DIR.glob("*.txt"))
    if not files:
        raise FileNotFoundError(f"No .txt files found in input directory: {INPUT_DIR}")
    return files


def get_lte_reference_file() -> Path:
    return _lte_reference_file_var.get() or LTE_REFERENCE_FILE


def get_nr_reference_file() -> Path:
    return _nr_reference_file_var.get() or NR_REFERENCE_FILE


def get_feature_reference_file() -> Path:
    return _feature_reference_file_var.get() or FEATURE_REFERENCE_FILE


def get_output_file() -> Path:
    return _output_file_var.get() or OUTPUT_FILE
